### ISSUE TITLE
un-doc'd changes between 1.1.0 and 1.2.0

### ISSUE THREAD

**Issue by jrochkind** [scsmith/language_list#19]
In 1.1.0, you can do `LanguageList::LanguageInfo.find(nil)`, and get `nil` back. In 1.2.0, you get 

~~~
NoMethodError: undefined method `downcase!' for nil:NilClass
	from /Users/jrochkind/.gem/ruby/2.4.0/gems/language_list-1.2.0/lib/language_list.rb:65:in `find'
~~~

Probably related, it's also mutating the argument passed in. 

~~~
str = "German"
LanguageList::LanguageInfo.find(str)
str # is now "german" not "German"
~~~

I don't want it mutating the arguments passed in, that's a bad practice. 

Both of these things caused my build to fail upgrading from 1.1.0 to 1.2.0

**Comment by tmaier** [comment]
Indeed, this is a regression.
I have with the same line of code also an issue, for which I created already a Pull Request.

Here is the diff of `v1.1.0` and `v1.2.0`: https://github.com/scsmith/language_list/compare/v1.1.0...v1.2.0

**Comment by tmaier** [comment]
I added now tests and a fix for #19 to #20
